# Generated by Django 4.0.5 on 2022-06-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_budget_alter_video_fees'),
        ('actor', '0003_remove_actor_nationality_remove_actor_surname_and_more'),
        ('director', '0005_remove_director_surname'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='director',
        ),
        migrations.RemoveField(
            model_name='user',
            name='video',
        ),
        migrations.CreateModel(
            name='FavouriteVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ManyToManyField(blank=True, related_name='user', to='video.video', verbose_name='Любимые видео')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ManyToManyField(blank=True, related_name='user', to='director.director', verbose_name='Любимые режисёры')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ManyToManyField(blank=True, related_name='user', to='actor.actor', verbose_name='Любимые актёры')),
            ],
        ),
    ]
