# Generated by Django 4.0.5 on 2022-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('authentication', '0003_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actor',
            field=models.ManyToManyField(related_name='user', to='actor.actor', verbose_name='Любимые актёры'),
        ),
    ]
