# Generated by Django 4.0.5 on 2022-06-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_remove_actor_nationality_remove_actor_surname_and_more'),
        ('director', '0005_remove_director_surname'),
        ('video', '0004_alter_video_budget_alter_video_fees'),
        ('authentication', '0003_remove_user_actor_remove_user_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritedirector',
            name='director',
        ),
        migrations.RemoveField(
            model_name='favouritevideo',
            name='video',
        ),
        migrations.AddField(
            model_name='user',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='user', to='actor.actor', verbose_name='Любимый актёр'),
        ),
        migrations.AddField(
            model_name='user',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='user', to='director.director', verbose_name='Любимые режисёр'),
        ),
        migrations.AddField(
            model_name='user',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='user', to='video.video', verbose_name='Любимые видео'),
        ),
        migrations.DeleteModel(
            name='FavouriteActor',
        ),
        migrations.DeleteModel(
            name='FavouriteDirector',
        ),
        migrations.DeleteModel(
            name='FavouriteVideo',
        ),
    ]
