# Generated by Django 4.0.5 on 2022-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_remove_actor_nationality_remove_actor_surname_and_more'),
        ('director', '0005_remove_director_surname'),
        ('authentication', '0004_remove_favouritedirector_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='user', to='actor.actor', verbose_name='Любимые актёры'),
        ),
        migrations.AlterField(
            model_name='user',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='user', to='director.director', verbose_name='Любимые режисёры'),
        ),
    ]
