# Generated by Django 4.0.5 on 2022-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_actor'),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='director',
            field=models.ManyToManyField(related_name='user', to='director.director', verbose_name='Любимые режисёры'),
        ),
    ]
