# Generated by Django 4.0.5 on 2022-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='surname',
        ),
        migrations.AddField(
            model_name='actor',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthplace',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='Родился'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='dies',
            field=models.DateField(blank=True, null=True, verbose_name='Умер'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='actors/cover', verbose_name='Обложка'),
        ),
    ]
