# Generated by Django 4.0.5 on 2022-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='nationality',
        ),
        migrations.AddField(
            model_name='director',
            name='height',
            field=models.IntegerField(default=None, verbose_name='Рост'),
        ),
    ]
