# Generated by Django 4.0.5 on 2022-06-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_alter_director_birthplace_alter_director_born_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='surname',
        ),
    ]
