# Generated by Django 4.0.5 on 2022-06-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.TimeField(verbose_name='Продолжительнось')),
                ('release', models.DateField(verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=64, verbose_name='Старна')),
                ('age_restriction', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('fees', models.IntegerField(verbose_name='Сборы')),
                ('image_url', models.CharField(max_length=255, verbose_name='Ссылка на обложку')),
                ('video_url', models.CharField(max_length=255, verbose_name='Ссылка на трейлер')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
