# Generated by Django 4.0.5 on 2022-06-24 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0002_initial'),
        ('genre', '0002_initial'),
        ('video_type', '0002_initial'),
        ('director', '0002_initial'),
        ('studio', '0002_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на обложку')),
                ('video_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на трейлер')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.TimeField(verbose_name='Продолжительнось')),
                ('release', models.DateField(verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=64, verbose_name='Старна')),
                ('age_restriction', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('fees', models.IntegerField(verbose_name='Сборы')),
                ('actor', models.ManyToManyField(related_name='video', to='actor.actor', verbose_name='Актёры')),
                ('director', models.ManyToManyField(related_name='video', to='director.director', verbose_name='Режисёры')),
                ('genre', models.ManyToManyField(related_name='video', to='genre.genre', verbose_name='Жанр')),
                ('studio', models.ManyToManyField(related_name='video', to='studio.studio', verbose_name='Стyдия')),
                ('v_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='v_type', to='video_type.videotype')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
