# Generated by Django 4.0.5 on 2022-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_image_url_x2_alter_video_v_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='budget',
            field=models.CharField(max_length=64, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fees',
            field=models.CharField(max_length=64, verbose_name='Сборы'),
        ),
    ]
