# Generated by Django 4.0.5 on 2022-07-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_studio_cover_alter_studio_formation_year'),
        ('genre', '0003_alter_genre_cover_alter_genre_description'),
        ('video', '0004_alter_video_budget_alter_video_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(related_name='video', to='genre.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='video',
            name='studio',
            field=models.ManyToManyField(related_name='video', to='studio.studio', verbose_name='Стyдии'),
        ),
    ]
