# Generated by Django 4.0.5 on 2022-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='genres/cover', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
