# Generated by Django 4.0.5 on 2022-06-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('formation_year', models.DateField(verbose_name='Год основания')),
                ('cover', models.ImageField(upload_to='studios/cover', verbose_name='Обложка')),
                ('video', models.ManyToManyField(related_name='studio', to='video.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
            },
        ),
    ]
